### PR TITLE
Update test_project with editor examples

### PR DESCRIPTION
**Pull request by llazzaro**
This pull request adds a index view with link to different editors.

### CODE REVIEW

**Comment by mbi** [comment]
Hi, thanks for this PR, but unfortunately [it breaks all the tests](https://travis-ci.org/mbi/django-front/builds/631796789) :disappointed:

**Comment by llazzaro** [comment]
I forgot to run the tests, I will check it

**Comment by llazzaro** [comment]
I realized that I executed the tests, it seems that the `test_project` settings are overriding the user authentication and it's the cause of the failing tests.
I will check it later to see why `test_project/settings.py` are affecting the tests.

**Comment by llazzaro** [comment]
ok! I got it, tox.ini uses `python -Wd manage.py test front` to execute tests. I was running the tests with pycharm, which caused to pass in my environment.
Also fixed some import error with django 1.11 in last commit

**Comment by mbi** [comment]
I've been thinking about this... I'm not sure I want to expose actual test pages in the test project, as it's really just meant to run the test suite, and not quite to "play" with. I'm especially not too fond of the `TESTING` setting added to differentiate between testing and non-testing, as settings `DJANGO_FRONT_PERMISSION` to allow all to edit could potentially open a security risk. (although I'm not 100% sure of the vector)

So... wondering: what was your rationale in submitting this PR in the first place?

**Comment by llazzaro** [comment]
The idea was to have a sample project to see and test the project. However DJANGO_FRONT_PERMISSION can be deleted if this causes a doubts on security.
Without it, to test the project it's required to have a user with is_staff permission. I think is better to remove it, and show a message to the user.

I submitted this PR for anyone how want to test the project in a quick way and see how django-front works

**Comment by mbi** [comment]
> I submitted this PR for anyone how want to test the project in a quick way and see how django-front works

But the user will still have to 

0. Realize the test_project can be actually used to test the project, and not only to run tests
1. Create a virtualenv or install the requirements globally,  without really knowing what those requirements are
2. migrate to create an initial db
3. without `DJANGO_FRONT_PERMISSION`, they'll also have to edit the test_project's settings and urls to add an admin
4. create a superuser
5. log in and come back to the test page


A lot of work just to get there, when simply reading the documentation and directly installing into their own project, will get them up and running in a matter of seconds :man_shrugging:

**Comment by llazzaro** [comment]
ok! let's close this pr

**Comment by mbi** [comment]
Don't get me wrong, for development this is actually a good idea, and truth be said, I have a separate test_project which I don't commit because it contains all the closed-source editors I test with, but IMO documentation on how to get started and play with the project is more important than actually have a test_project which is both for running tests and playing with.

Anyway, thank you for the discussion and the PR!

**Comment by llazzaro** [comment]
Just an example of why I created this pr was this:
https://github.com/llazzaro/django-scheduler-sample

I found that a lot of people like to have a sample project for a quick test. 
I understand your point, dont worry!

**Pull request closed without merging**
